name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: Linux
    container:
      image: debian:stable

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install java and maven
      run: |
        apt-get update -y && \
        apt-get install -y maven openjdk-17-jdk-headless curl

    - name: Build with Maven
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      run: mvn -B package jacoco:report --file pom.xml

    - name: Coveralls
      uses: coverallsapp/github-action@v2

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      
