
name: Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: Linux
    container:
      image: debian:stable

    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install java and maven
      run: |
        apt-get update -y && \
        apt-get install -y maven openjdk-17-jdk-headless

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
